### Получить всех сотрудников
GET http://localhost:8080/employees
### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "department": 1,
  "salary": 1000

}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test2",
  "lastName": "Test2",
  "department": 2,
  "salary": 3000

}
### Получить сумму зарплат
GET http://localhost:8080/employees/salary/sum