### Получить всех сотрудников
GET http://localhost:8080/employees
### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "department": 1,
  "salary": 10000

}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "TestTwo",
  "lastName": "TestTwo",
  "department": 2,
  "salary": 30000

}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "TestThree",
  "lastName": "TestThree",
  "department": 1,
  "salary": 76000

}
### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "TestFour",
  "lastName": "TestFour",
  "department": 2,
  "salary": 65000

}
### Создать сотрудника 5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "TestFive",
  "lastName": "TestFive",
  "department": 3,
  "salary": 76000

}
### Получить сумму зарплат
GET http://localhost:8080/employees/salary/sum
### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min
### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max
### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/high-salary